
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgypojvxyzoqwyikbjda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneXBvanZ4eXpvcXd5aWtiamRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MTkxNTUsImV4cCI6MjA1NzQ5NTE1NX0.I91Jjpnoc830XPXSLtHABjDk_bRt8Wk8zDJybaa_Drw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export type Profile = {
  id: string;
  name: string | null;
  role: string | null;
  avatar_url: string | null;
};

// Create Supabase client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Sign up dengan email dan password
export const signUp = async (email: string, password: string, userData: any) => {
  const { data, error } = await supabase.auth.signUp({
    email,
    password,
    options: {
      data: userData,
    }
  });
  
  return { data, error };
};

// Login dengan email dan password
export const signIn = async (email: string, password: string) => {
  const { data, error } = await supabase.auth.signInWithPassword({
    email,
    password,
  });
  
  return { data, error };
};

// Logout
export const signOut = async () => {
  const { error } = await supabase.auth.signOut();
  return { error };
};

// Get current session
export const getSession = async () => {
  const { data, error } = await supabase.auth.getSession();
  return { data, error };
};

// Get user profile
export const getUserProfile = async (userId: string) => {
  const { data, error } = await supabase
    .from('profiles')
    .select('*')
    .eq('id', userId)
    .single();
  
  return { data, error };
};

